#!/bin/sh

# GitHub or Dockerhub name/project of the source project you want to keep up-to-date-with
SOURCE="mehtadone/PTFeeder"

# Your GitHub name/project for this project
REPO="m59peacemaker/docker-profit-trailer-feeder"

# docker image name/project for local/dev builds
IMAGE="pmkr/profit-trailer-feeder"
